# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme = maclight

@background = #fdfdfdff
@accentBase2Color = #2a3b72ff

@accentBaseColor = #772c4dff
@buttonBackground = @accentBaseColor
@accentSliderColor = @accentBaseColor

@foreground = #1f2224
@buttonHoverArrowColor = @accentBase2Color
@buttonPressedArrowColor = #db9c36ff
@nsTextColor = @foreground
Button.borderColor = = #db9c36ff